name: pydora_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - click=7.0
  - pandas=1.0.1
  - pymysql=1.0.2
  - python=3.8.2
  - sqlalchemy=1.3.13
  - tqdm=4.43.0
  - sphinx=3.4.3
  - sphinx-click=2.5.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-napoleon=0.7
  - sphinxcontrib-qthelp=1.0.3
  - sphinx_rtd_theme=0.5.1
  - sphinxcontrib-serializinghtml=1.1.4
  - alabaster=0.7.12
  - nbsphinx=0.8.1
  - recommonmark=0.7.1


